# Generated by Django 5.0.7 on 2024-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributor',
            field=models.CharField(max_length=255),
        ),
    ]
